class Locators:
    
    login_and_registration_button = ".//button[text()='Вход и регистрация']"
    login_form = ".//form[contains(@class, 'popUp')]//h1[text()='Войти']"
    no_account_button = ".//button[text()='Нет аккаунта']"
    registration_form = ".//form[contains(@class, 'popUp')]//h1[text()='Зарегистрироваться']"
    create_account_button = ".//button[text()='Создать аккаунт']"
    email_input_error = ".//input[@name='email']/parent::*[contains(@class, 'inputError')]"
    password_input_error = ".//input[@name='password']/parent::*[contains(@class, 'inputError')]"
    submit_password_input_error = ".//input[@name='submitPassword']/parent::*[contains(@class, 'inputError')]"
    email_input_error_text = ".//input[@name='email']/parent::*[contains(@class, 'inputError')]/parent::div/parent::div/span[text()='Ошибка']"
    email_input_error_span = ".//input[@name='email']/parent::*[contains(@class, 'inputError')]/parent::div/parent::div/span"
    login_button = ".//button[text()='Войти']"
    logout_button = ".//button[text()='Выйти']"
    place_an_ad_button = ".//button[text()='Разместить объявление']"
    place_ad_login_form = ".//form[contains(@class, 'popUp')]//h1[text()='Чтобы разместить объявление, авторизуйтесь']"
    new_ad_title = ".//h1[text()='Новое объявление']"
    ad_name_input = ".//input[@name='name']"
    category_dropDown_button = ".//input[@name='category']/parent::div[contains(@class, 'dropDownMenu_input')]/button[contains(@class,'dropDownMenu')]"
    category_dropDown_gardening_button = ".//button[contains(@class,'dropDownMenu_btn')]/span[text()='Садоводство']"
    city_dropDown_button = ".//input[@name='city']/parent::div[contains(@class, 'dropDownMenu_input')]/button[contains(@class,'dropDownMenu')]"
    city_dropDown_novosibirsk_button = ".//button[contains(@class,'dropDownMenu_btn')]/span[text()='Новосибирск']"
    bu_radio_input = ".//input[@value='Б/У']/parent::div[contains(@class, 'radioUnput_shell')]/div[contains(@class, 'radioUnput_inputRegular')]"
    ad_textarea_description = ".//textarea[@name='description']"
    ad_price_input = ".//input[@name='price']"
    ad_publish_button = ".//button[text()='Опубликовать']"
    main_page_search_input = ".//input[contains(@placeholder,'Я хочу купить')]"
    profile_title = ".//h1[text()='Мой профиль']"
    ad_pagination = ".//div[contains(@class,'pagination')]"
    cards_with_mandragora_title = ".//div[@class='card']//h2[contains(text(), 'Мандрагора')]"
    cards_with_mandragora_city = ".//div[@class='card']//h2[text()='Мандрагора']/parent::div[@class='about']/h3"